dist: xenial
sudo: required
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_2713a52fe9aa_key -iv $encrypted_2713a52fe9aa_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.58.1
  - secure: iqxB6b+Skx69blXlNuGWXyGfyrSf1X8pwj7UI+feT0GLE1CaVa2DLPhmI7QhXO0DBSXvqDdOmlFBZEibaFd0AIfDJdI/z43sErXfQuOE54xNk/avlwAhWxrUIpIgZRtMNGzTvBTGG2gz09mGuyaeNbyZK+WQHaRnERQdQOPAC4Z1TbEx2MkPrku7CwM+nxb6wGKQDq/bvcXdp2rrSeFD+mzLYkGoLCA5crLaEaGJBqb1XVSIBMdUV9ysaqLgqXQcJuD9/AtZDbn3nISvG2+UbGkW5EDtMvSL3nCx9JIzVubut62q/5bkjewthHKUjFhSkVr2Dl96vDh+SEzd+cHHA+Nw5XB281rLKpL3pqwtoWWBPs3LLgMAvu5b+jIc+0rcm96G57rUkJHT+Shyd9NJkP3N3tTEByHPwxeLhUnXn11nPyZClZrqK8UIUFzE/0ysscGNNlJsMlgT5TaN6GWAPDucyq9C3Iose8rs+XFABCY9qehPfX7lp7WTQMLG7KrNZ1Wof5yjDDpi9GYALTcAF6vRF1t6ea66Pv07thUMw1ZsW3+h1K55Nb/bPCE5I5TeBJZVNlbId+BM7DIJBUHK7lMl8LbvjCOmpxY3qk2Mj2Trnf/BJYS4iFZqavF8stf/7xDKP602rJsYeicFNh28JIoAUmluZp9QkexKEH32PU8=
  - secure: LGNeTdxZW28GBok5YAAcR0oHyalfCqH4roO99EQOO/wwOmPyJV4KyGf2FPVxxdKZ0hgnH092zxcR475o+RsaooPdCsZz0JmUkm4FImeho/0gYEE8iv9QSGXZKvFQPLEwlqoFE0t/RIrHqEmOhPogNaFqp032DAmOBikb93PvWENyG5sDmpo5PklZTpGrwzrihs5Q8UH87ZFd+/kmq0wCB/7XRXALdcw4hV0KRVHbWaZ3PWdhd8pSj98Hr0nnTSljso2WTE5fDznfqOmcMrudbjUvxx/wsSHsX+k9e+CVdzrxlrcT98JSHdom0NpLtroTqhwJFdosefLcAVfQfYSwkscunv3EfxwPx6S50Au4pieBsc4pYMshFqyJ7E8xqV/o6v44t6QPPSe+MQdt5IqaXOmcn3GLCDECbtGxmkvDbMI3xhlMA2kH/yqyVZD8oAaSSbF//nnbsnxieO1QoB4Ozo1jHN4HLY57Pv6AlEDosOhebh98J6lZjcs+El8k5Uy3O6OF0dv6Y79WGjdsFOx2Sz1/fFJNxRFJ0fZQZgFqdohGUpAbEssY3tSfJ14OLvrSwlGjdQil5ce40/O2Xm1QtoyZ4QEsKQMXZXFNvqd982di3p4xa3CvNALLwFRUUU1XwHqDBVH5MtVnUI7LXRFOFs1H2lJjUchDWDU2psTBiFg=
  - secure: QdkC/pksFuR0S0g3ctiLJssfCBiEmGkvnNMU51d1UOCh7BWGvRa95zaySjvVJXN2OLef77oTqejSLQa2TM0iBqfypuY9vwYRdv4oASaxfhkAfMLF3qVCF7YPDzOudHLi/vsiqGDbo9JkkSnKIYtnw84PXYFPsE2W1GjCkbWD4UirrW/h9QkbzHxGvD5StTlqsa97YsNTKX6v4dzm8MMgCSU7rr3PpEutBVV8VoXuhCuztocm1OfrgIVrNN/kDc9KWA+Kk1cLSCdlskVF9gMwKRyMAKN6eH1e8E28ZQn1fUMzsNU4pUTc8zCQgu1lFYf9se9TqKXlo2kQcqsoEh9viNTs+IgAYYuYMgY+861ebZ6baX0fvleB/kw6E1/6Sqpb4atYftIB/UG647ZgMpq3//xn8VsHvoHLGU1wfIxw61xWqGbL402dyd8t8a4e/0/2Ig41t4jopYRaEcUeX9OY4xn4i25nIVQd1qGDv0fDkNFJ5ZiM4C3/c7ShNN4HCCRw16vh9+PxQEHbIOAkDIRoCe3GNBKDJwtIoieOezBLPsm6IAp21JMI/4U3eHM6lkHV6PwvX15DZEXEBkzI1uP9mzwurUfFJOr9HY7vCSN4e+qlZlTA3gRs0gr0z88qVnjlm9lYkozhJtPKYdyqyPCG22SaIR4GY3QDFTZILaOQwIg=
