DefaultContentLanguage = "en"
baseurl = ""
disableLanguages = [""]
disqusShortname = ""
googleAnalytics = ""
paginate = 5
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect-slim"
title = "Hugo Future Imperfect Slim"
[[menu.main]]
name = "Admin"
pre = "<i class='far fa-edit'></i>"
url = "admin/"
weight = 3
[[menu.main]]
name = "Categories"
pre = "<i class='fas fa-sitemap'></i>"
url = "categories/"
weight = 2
[[menu.main]]
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "blog/"
weight = 1
[params]
cssFiles = ["default"]
highlightjs = true
highlightjsLang = ["html", "css", "js", "toml"]
highlightjsTheme = "github"
jsFiles = ["default"]
mainSections = ["blog", "post"]
readingTime = true
viewMorePostsLink = "/blog/"
[params.footer]
rssFooter = true
[params.header]
dynamicTitles = true
languageMenu = false
navbarTitle = "Home"
searchMenu = true
shareMenu = false
[params.intro]
rssIntro = true
[params.intro.pic]
alt = "Hugo Future Imperfect Slim"
shape = "circle"
src = "/img/main/logo.jpg"
width = ""
[params.meta]
favicon = false
faviconVersion = "1"
iOSColor = "#ffffff"
msColor = "#ffffff"
svg = true
[params.sidebar]
about = "about"
categories = true
categoriesByCount = true
postAmount = 5
[params.staticman]
api = ""
branch = ""
enabled = false
gitProvider = "github"
repo = ""
username = ""
[params.staticman.recaptcha]
encryptedKey = ""
siteKey = ""
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
foursquare = ""
gitlab = ""
googleplus = ""
googlescholar = ""
jsfiddle = ""
medium = ""
orcid = ""
qq = ""
quora = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
tumblr = ""
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
